# Configuration Settings for C94-M8P device

debug: 1                    # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM1
frame_id: gps
rate: 4                     # in Hz
nav_rate: 4                 # [# of measurement cycles], recommended 1 Hz, may 
                            # be either 5 Hz (Dual constellation) or 
                            # 8 Hz (GPS only)
dynamic_model: airborne2    # Airborne < 2G, 2D fix not supported (3D only), 
                            # Max Alt: 50km
                            # Max Horizontal Velocity: 250 m/s, 
                            # Max Vertical Velocity: 100 m/s
fix_mode: auto
enable_ppp: false           # Not supported by C94-M8P
dr_limit: 0

uart1:
  baudrate: 19200           # C94-M8P specific
  in: 32                    # RTCM 3
  out: 0                    # No UART out for rover

gnss:
  reset_mode: 2             # Controlled Software reset
  glonass: true             # Supported by C94-M8P
  beidou: false             # Supported by C94-M8P
  qzss: false               # Supported by C94-M8P
  sbas: false               # Not supported by C94-M8P

dgnss_mode: 3               # Fixed mode

inf: true                   # Whether to display INF messages

# Subscriptions
subscribe:
  all: true
  aid: true
  aid:
    hui: false

  nav:
    sol: true
    pvt: true
    status: true
    svinfo: true
    svin: true
    clk: true
    posecef: false
    velned: false
    relposned: true
